fboss/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('games.urls')),
]

games/urls.py
from django.urls import path
from . import views

app_name = 'games'
urlpatterns = [
    path('', views.home, name='home'),
    path('games/about/', views.about, name='about'),
    path('games/all_games/', views.ListGames.as_view(), name='all_games'),
    path('games/new/', views.CreateGame.as_view(), name='new'),
    path('games/update/<pk>', views.UpdateGame.as_view(), name='update'), 
    path('games/delete/<pk>', views.DeleteGame.as_view(), name='delete'),
    path('games/kw_filter/', views.KeywordFilter.as_view(), name='kw_filter'),
    path('games/plat_filter/', views.PlatformFilter.as_view(), name='plat_filter'),
    path('games/score_filter/', views.ScoreFilter.as_view(), name='score_filter'),
    path('games/score_plat_filter/', views.ScorePlatFilter.as_view(), name='score_plat_filter'),
    path('games/api_kw/', views.api_kw, name='api_kw'),
    path('games/api_ss/', views.api_ss, name='api_ss'),
    path('games/api_tr/', views.api_tr, name='api_tr'),
    path('games/csv_upload/', views.csv_upload, name='csv_upload'),
    path('games/stats/', views.stats, name='stats')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('<str:username>/', views.ProfileView.as_view(), name='profile')
]

games/models.py
from django.db import models
from django.urls import reverse

class Game(models.Model):
    owner = models.ForeignKey('auth.User', related_name='games', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    platform = models.CharField(max_length=100)
    score = models.IntegerField()

    def __str__(self):
        return f'{self.title} - {self.platform} - {self.score}'

    class Meta:
        ordering = ['platform', 'title']

    def get_absolute_url(self):
        return reverse('games:home', args=(self.pk,))

users/models.py
from django.db import models

# Create your models here.

games/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.db.models import Q
from django.contrib import messages
import csv, io

from .models import Game

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html') 

def api_kw(request):
    return render(request, 'api_kw.html')

def api_ss(request):
    return render(request, 'api_ss.html')

def api_tr(request):
    return render(request, 'api_tr.html')  

def stats(request):

    count = Game.objects.all().count()
     
    plat_count = []

    formats = []

    formats_list = []

    game_count = []

    format_gamelist = []

    platforms = Game.objects.values("platform")

    for platform in platforms:
        if platform not in plat_count:
            plat_count.append(platform)

    for platform in plat_count:
        formats.append(platform)

    for format in formats:
        game_array = Game.objects.filter(platform=format["platform"])
        game_count.append(len(game_array))
        formats_list.append(format["platform"])

    format_gamelist = {formats_list[i]: game_count[i] for i in range(len(formats_list))}

    result = list(format_gamelist.items())

    plat_count = len(plat_count)

    context = {'count': count,
            'plat_count': plat_count,
            'result': result
            }

    return render(request, 'stats.html', context)              

class ListGames(ListView):
    model = Game
    template_name = 'all_games.html'

class KeywordFilter(ListView):
    model = Game
    template_name = "kw_filter.html"

    def get_queryset(self): 
        query = self.request.GET.get("kw", default="")
        object_list = Game.objects.filter(title__contains=query)
        return object_list    

class PlatformFilter(ListView):
    model = Game
    template_name = "plat_filter.html"

    def get_queryset(self): 
        query = self.request.GET.get("plat", default="")
        object_list = Game.objects.filter(platform__exact=query)
        return object_list    

class ScoreFilter(ListView):
    model = Game
    template_name = "score_filter.html"

    def get_queryset(self): 
        query = self.request.GET.get("score", default=0)
        object_list = Game.objects.filter(score__gte=query)
        return object_list

class ScorePlatFilter(ListView):
    model = Game
    template_name = "score_plat_filter.html"

    def get_queryset(self):
        query1 = self.request.GET.get("plat", default="") 
        query2 = self.request.GET.get("score", default=0)
        object_list = Game.objects.filter(Q(platform__exact=query1) & Q(score__gte=query2))
        return object_list
  
class CreateGame(LoginRequiredMixin, CreateView):
    model = Game
    template_name = 'new_game.html'
    fields = ['title', 'platform', 'score']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    success_url = reverse_lazy('games:all_games')    

class UpdateGame(LoginRequiredMixin, UpdateView):
    model = Game
    template_name = 'update.html'
    fields = ['title', 'platform', 'score']

    success_url = reverse_lazy('games:all_games')

class DeleteGame(LoginRequiredMixin, DeleteView):
    model = Game
    template_name = 'delete.html'
    fields = ['title', 'platform', 'score']

    success_url = reverse_lazy('games:all_games')

def csv_upload(request): 
    template = "csv_upload.html"
    data = Game.objects.all()
    prompt = {
        'order': 'Order of the CSV should be [title, platform, score]',
        'profiles': data    
              }
    if request.method == "GET":
        return render(request, template, prompt) 

    csv_file = request.FILES['file']

    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'THIS IS NOT A CSV FILE') 
        
    data_set = csv_file.read().decode('UTF-8')

    io_string = io.StringIO(data_set)
    next(io_string)
    for column in csv.reader(io_string, delimiter=',', quotechar="|"):
        _, created = Game.objects.update_or_create(
            title=column[0],
            platform=column[1],
            score=column[2],
            owner_id=request.user.id
        )
    context = {}
    return render(request, template, context)  

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404


class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('login')


class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'profile.html'
    context_object_name = 'user_profile'

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs['username'])

templates/api_kw.html
{% extends 'base.html' %}
{% block additional_styles %}
<style>
body {
    background-image: url("/static/images/akuma.jpg");
}
</style>
{% endblock %}

{% block content %}

    <div id="api_kw">

        <h1>Keyword Search</h1><br>

        <input id="kw_input" type="text" placeholder="Enter search term"><br><br>

        <button onclick="getKw()">Search</button><br><br>

        <div class="div_sub" id="api_kw_sub">

        </div>   
    
    </div>
                
{% endblock %}

templates/api_ss.html
{% extends 'base.html' %}
{% block additional_styles %}
<style>
body {
    background-image: url("/static/images/akuma.jpg");
}
</style>
{% endblock %}

{% block content %}

    <div id="api_ss">

        <h1>Screenshot Search</h1><br>

        <input id="ss_input" type="text" placeholder="Enter search term"><br><br>

        <button onclick="getSs()">Search</button><br><br>

        <div class="div_sub" id="api_ss_sub">

        </div>   
    
    </div>
                
{% endblock %}

templates/api_tr.html
{% extends 'base.html' %}
{% block additional_styles %}
<style>
body {
    background-image: url("/static/images/akuma.jpg");
}
</style>
{% endblock %}

{% block content %}

    <div id="api_tr">

        <h1>Trailer Search</h1><br>

        <input id="tr_input" type="text" placeholder="Enter search term"><br><br>

        <button onclick="getTr()">Search</button><br><br>

        <div class="div_sub" id="api_tr_sub">

        </div>   
    
    </div>
                
{% endblock %}

templates/base.html
{% load static %}
{% block additional_styles %}
<style>
    body {
    background: url("/static/images/ganondorf.jpg");
    }
</style>
{% endblock %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script src="{% static 'scripts/script.js' %}" defer></script>
    <title>FinalBoss CRT</title>
</head>
<body>
    <nav>
    <div id="title">
        <h1><a href="{% url 'games:home' %}">FinalBoss CRT</a></h1>
    </div>
    <div id="subtitle">  
        <h4><a href="{% url 'games:about' %}">'herder of chaos...slayer of backlogs'</a></h4>
    </div>
    <div id="login">
        {% if user.is_authenticated %}

        <a href="{% url 'users:profile' user.username %}">{{user.username}}</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'logout' %}">Logout</a>
        
        {% else%}
        <a href="{% url 'login' %}">Login</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'users:signup' %}">Register</a>
        
        {% endif %}
    </div>
    </nav> 
    
    {% block content %}
    {% endblock %}

    <footer id="footer">Copyright © 2022&nbsp;<a href="https://www.linkedin.com/in/michael-jackson-pdx71/">Michael J. Jackson</a></footer>

</body>
</html>

templates/csv_upload.html
{% extends 'base.html' %}
{% block additional_styles %}
<style>
body {
    background-image: url("/static/images/GLaDOS.jpg");
}
</style>
{% endblock %}

{% block content %}

    <div id="csv_upload">

        {% if messages %}
        {% for message in messages %}
            <div>
                <strong>{{message|safe}}</strong>
            </div>
        {% endfor %}
        {% else %}
        {{order}}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" id="file1" name="file">
            <button type="submit">Upload</button>
        </form>
        {% endif %}
        {% for profile in profiles %}
        {{profile.name}}
        {% endfor %}

    </div>    

{% endblock %}    

templates/delete.html
{% extends 'base.html' %}
{% block additional_styles %}
<style>
body {
    background-image: url("/static/images/malus.jpg");
}
</style>
{% endblock %}

{% block content %}

    <div id="delete">
        <h1>Delete Game Record</h1><br>
        <h4>This will delete <span id="dlt_game">{{ game.title }}</span> from the database.</h4><br>
        <h4>If you are sure you want to delete this record click 'Delete' below.</h4><br><br>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Delete">
        </form>
    </div>
                
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}
        <div id="main">
            <ul>
                <li><a href="{% url 'games:all_games' %}">Game Collection Database</a></li><br>
                <li><a href="{% url 'games:kw_filter' %}">Filter Collection by Keyword</a></li><br>
                <li><a href="{% url 'games:plat_filter' %}">Filter Collection by Platform</a></li><br>
                <li><a href="{% url 'games:score_filter' %}">Filter Collection by Minimum Score</a></li><br>
                <li><a href="{% url 'games:score_plat_filter' %}">Filter Collection by Score/Platform </a></li><br>
                <li><a href="{% url 'games:api_kw' %}">Search for Games Online</a></li><br>
                <li><a href="{% url 'games:api_ss' %}">Search for Screenshots Online</a></li><br>
                <li><a href="{% url 'games:api_tr' %}">Search for Trailers Online</a></li>
            </ul> 
        </div>
    {% else %} 
    
        <div id="landing">
            <h4>Please <a href="{% url 'login' %}">login</a> or <a href="{% url 'users:signup' %}">register</a> to begin managing your personal game collection with FinalBoss</h4>
        </div>

    {% endif %}       

{% endblock %}

templates/kw_filter.html
{% extends 'base.html' %}
{% block additional_styles %}
<style>
body {
    background-image: url("/static/images/GLaDOS.jpg");
}
</style>
{% endblock %}

{% block content %}

    <div id="kw_filter">

        <h1>Keyword Filter</h1><br>

        <form action="{% url 'games:kw_filter' %}" method="get">
            <input name="kw" type="text" placeholder="Enter search term">
            <input type="submit" value="Filter">
        </form><br>

        <div class="div_sub">

            {% for game in object_list %}

                <div>

                    {% if user == game.owner %}

                        {{ game.title }}, {{ game.platform }}, {{ game.score }}...<a href="{% url 'games:update' game.id %}"><i class="material-icons" style="font-size:14px;">edit</i></a>  <a href="{% url 'games:delete' game.id %}"><i class="material-icons" style="font-size:14px;">delete</i></a>

                    {% endif %}   

                </div>

            {% endfor %}

        </div>    
    
    </div>
                
{% endblock %}

templates/new_game.html
{% extends 'base.html' %}
{% block additional_styles %}
<style>
body {
    background-image: url("/static/images/sephiroth.jpg");
}
</style>
{% endblock %}

{% block content %}

    <div id="new_game">
        <h1>Create New Record</h1><br>
        <form action="{% url 'games:new' %}" method="post">
            {% csrf_token %}
            <input type='text' placeholder='title' name='title'>
            <input type='text' placeholder='platform' name='platform'>
            <input type='number' placeholder='score' name='score' >
            <input type="submit" value="Save">
        </form>
    </div>
                
{% endblock %}

templates/plat_filter.html
{% extends 'base.html' %}
{% block additional_styles %}
<style>
body {
    background-image: url("/static/images/GLaDOS.jpg");
}
</style>
{% endblock %}

{% block content %}

    <div id="plat_filter">

        <h1>Platform Filter</h1><br>

        <form action="{% url 'games:plat_filter' %}" method="get">
            <input name="plat" type="text" placeholder="Enter platform">
            <input type="submit" value="Filter">
        </form><br>

        <div class="div_sub">

            {% for game in object_list %}

                <div>

                    {% if user == game.owner %}

                        {{ game.title }}, {{ game.platform }}, {{ game.score }}...<a href="{% url 'games:update' game.id %}"><i class="material-icons" style="font-size:14px;">edit</i></a>  <a href="{% url 'games:delete' game.id %}"><i class="material-icons" style="font-size:14px;">delete</i></a>

                    {% endif %}   

                </div>

            {% endfor %}

        </div>    
    
    </div>
                
{% endblock %}

templates/post_new.html
{% extends 'base.html' %}
{% block content %}
    <div id="new_post">
        <h1>New Game</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    </div>

{% endblock %}

templates/score_plat_filter.html
{% extends 'base.html' %}
{% block additional_styles %}
<style>
body {
    background-image: url("/static/images/GLaDOS.jpg");
}
</style>
{% endblock %}

{% block content %}

    <div id="score_plat_filter">

        <h1>Score by Platform Filter</h1><br>

        <form action="{% url 'games:score_plat_filter' %}" method="get">
            <input name="plat" type="text" placeholder="Enter platform">
            <input name="score" type="number" placeholder="Enter min score">
            <input type="submit" value="Filter">
        </form><br>

        <div class="div_sub">

            {% for game in object_list %}

                <div>

                    {% if user == game.owner %}

                        {{ game.title }}, {{ game.platform }}, {{ game.score }}...<a href="{% url 'games:update' game.id %}"><i class="material-icons" style="font-size:14px;">edit</i></a>  <a href="{% url 'games:delete' game.id %}"><i class="material-icons" style="font-size:14px;">delete</i></a>

                    {% endif %}   

                </div>

            {% endfor %}

        </div>    
    
    </div>
                
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block additional_styles %}
<style>
   body {
    background-image: url("/static/images/mewtwo.jpg");
   }
</style>
{% endblock %}
    
{% block content %}

    <div id="register_div">
        <h1>Register</h1><br>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Register">
        </form>

    </div>

{% endblock content %}

templates/update.html
{% extends 'base.html' %}
{% block additional_styles %}
<style>
   body {
    background-image: url("/static/images/viper.jpg");
   }
</style>
{% endblock %}

{% block content %}

    <div id="update">
        <h1>Update Game Record</h1><br>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    </div>
                  
{% endblock %}